# File:   Makefile
# Author: M. P. Hayes, UCECE
# Date:   11 Sep 2010
# Descr:  Makefile for spacey_remote1

CC = gcc
CFLAGS = -Wall -Wstrict-prototypes -Wextra -g -I. -I../../utils -I../../drivers -I../../drivers/test

DEL = rm


# Default target.
all: spacey_remote1


# Compile: create object files from C source files.
timer-test.o: ../../drivers/test/timer.c ../../drivers/test/timer.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

display-test.o: ../../drivers/display.c ../../drivers/ledmat.h ../../drivers/display.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

pio-test.o: ../../drivers/test/pio.c
	$(CC) -c $(CFLAGS) $< -o $@

ir_serial-test.o: ../../drivers/ir_serial.c ../../drivers/ir.h ../../drivers/ir_serial.h ../../drivers/test/delay.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

pacer-test.o: ../../utils/pacer.c ../../drivers/test/timer.h ../../utils/pacer.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

spacey_remote1-test.o: spacey_remote1.c ../../drivers/navswitch.h ../../drivers/ir_serial.h ../../drivers/test/system.h ../../utils/font.h ../../utils/tinygl.h ../../utils/pacer.h ../../drivers/display.h ../../drivers/ir.h ../../fonts/font5x7_1.h
	$(CC) -c $(CFLAGS) $< -o $@

ir-test.o: ../../drivers/ir.c ../../drivers/test/pio.h ../../drivers/ir.h ../../drivers/test/avrtest.h ../../drivers/test/delay.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

ledmat-test.o: ../../drivers/ledmat.c ../../drivers/test/avrtest.h ../../drivers/test/pio.h ../../drivers/ledmat.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

tinygl-test.o: ../../utils/tinygl.c ../../drivers/display.h ../../utils/font.h ../../utils/tinygl.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

system-test.o: ../../drivers/test/system.c ../../drivers/test/pio.h ../../drivers/test/avrtest.h ../../drivers/test/mgetkey.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

mgetkey-test.o: ../../drivers/test/mgetkey.c ../../drivers/test/mgetkey.h
	$(CC) -c $(CFLAGS) $< -o $@

navswitch-test.o: ../../drivers/navswitch.c ../../drivers/test/pio.h ../../drivers/navswitch.h ../../drivers/test/avrtest.h ../../drivers/test/delay.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@




# Link: create executable file from object files.
spacey_remote1: timer-test.o display-test.o pio-test.o ir_serial-test.o pacer-test.o spacey_remote1-test.o ir-test.o ledmat-test.o tinygl-test.o system-test.o mgetkey-test.o navswitch-test.o
	$(CC) $(CFLAGS) $^ -o $@ -lrt


# Clean: delete derived files.
.PHONY: clean
clean: 
	-$(DEL) spacey_remote1 timer-test.o display-test.o pio-test.o ir_serial-test.o pacer-test.o spacey_remote1-test.o ir-test.o ledmat-test.o tinygl-test.o system-test.o mgetkey-test.o navswitch-test.o


