# File:   Makefile
# Author: M. P. Hayes, UCECE
# Date:   11 Sep 2010
# Descr:  Makefile for task1

CC = gcc
CFLAGS = -Wall -Wstrict-prototypes -Wextra -g -I. -I../../utils -I../../drivers -I../../drivers/test

DEL = rm


# Default target.
all: task1


# Compile: create object files from C source files.
timer-test.o: ../../drivers/test/timer.c ../../drivers/test/timer.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

led-test.o: ../../drivers/led.c ../../drivers/led.h ../../drivers/test/pio.h ../../drivers/test/avrtest.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

pio-test.o: ../../drivers/test/pio.c
	$(CC) -c $(CFLAGS) $< -o $@

task-test.o: ../../utils/task.c ../../drivers/test/timer.h ../../utils/task.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

task1-test.o: task1.c ../../drivers/led.h ../../drivers/test/timer.h ../../utils/task.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

system-test.o: ../../drivers/test/system.c ../../drivers/test/pio.h ../../drivers/test/avrtest.h ../../drivers/test/mgetkey.h ../../drivers/test/system.h
	$(CC) -c $(CFLAGS) $< -o $@

mgetkey-test.o: ../../drivers/test/mgetkey.c ../../drivers/test/mgetkey.h
	$(CC) -c $(CFLAGS) $< -o $@




# Link: create executable file from object files.
task1: timer-test.o led-test.o pio-test.o task-test.o task1-test.o system-test.o mgetkey-test.o
	$(CC) $(CFLAGS) $^ -o $@ -lrt


# Clean: delete derived files.
.PHONY: clean
clean: 
	-$(DEL) task1 timer-test.o led-test.o pio-test.o task-test.o task1-test.o system-test.o mgetkey-test.o


